#!/usr/bin/env ruby

require 'slim'
require 'pathname'

photos = Dir.glob('./site/photos/orig/*.JPG').map do |path|
  Pathname(path).basename
end

result = Slim::Template.new("index.slim").render(nil, photos: photos)
Pathname('site/index.html').write(result)

