#!/usr/bin/env bash

if [ "$1" = "--all" ]; then
  echo "Resizing all files in ./site/photos/orig..."
  for filename in $(ls -l1 ./site/photos/orig/); do
    resize $filename
  done
else
  echo "Resizing $1..."
  convert ./site/photos/orig/$1 -resize 1000 -quality 75 ./site/photos/med/$1
  convert ./site/photos/orig/$1 -resize 3000 -quality 80 ./site/photos/lg/$1
fi
